### ISSUE TITLE
?name=special%20characters

### ISSUE THREAD

**Issue by lindell** [lindell/DISCO#1]
Problems exist with old links being double url encoded

**Comment by lindell** [comment]
http://disco.fleo.se/?name=( ͡° ͜ʖ ͡°)
vs
http://disco.fleo.se/( ͡° ͜ʖ ͡°)

**Comment by gustavkj** [comment]
I don't know if this is worth fixing. The issue seems to have solved it self. Little to no traffic contain the old query param. Should we close this?
